### ISSUE TITLE
Update package version on pypi

### ISSUE THREAD

**Issue by markbao** [mrtazz/simplenote.py#14]
Hey @mrtazz, thanks for your great work on this package so far. I was confused when installing it with pip from pypi since I couldn't get `get_note_list` to work with the `since` param. Turns out the [version on pypi](https://pypi.python.org/pypi/simplenote/0.2.0) is 0.2.0.

Luckily, `pip install git+https://github.com/mrtazz/simplenote.py.git` did the trick for now, but it might be a good idea to update it to 0.3.1 on pypi.

Thanks!
Mark

**Comment by atomicules** [comment]
I'll try to push a new tagged version to see if deploying now works 
via Travis. Unfortunately there have been bugs on Travis that have 
affected deploying, but apparently these finally got fixed this week.

**Comment by atomicules** [comment]
Just tried pushing a couple of tagged commits (one annotated and one 
lightweight) and Travis is reporting "Skipping deployment with the 
pypi provider because this is not a tagged commit".

Which at least is a different message that the one I used to get. 
Still doesn't help though!

**Comment by atomicules** [comment]
Hi @mrtazz could you please check that your PyPi password was encrypted 
correctly when you added it to `.travis.yml`?

Managed to get a response from someone at Travis and they seem to 
think the reason why it's not deploying is due to a problem with the 
password decrypting:

https://github.com/travis-ci/travis-ci/issues/1675#issuecomment-74426817

They mention reviewing the docs. I assume they mean the bit about 
escaping certain characters:

http://docs.travis-ci.com/user/encryption-keys/

Alternatively, would adding me as a maintainer on PyPi allow me to 
deploy using my PyPi credentials?

**Comment by mrtazz** [comment]
Hey atomicules. I'll take a look a the documentation to see if the encryption is wrong. I don't have a lot of experience with PyPi maintainer stuff, but I'll also look into that.

**Comment by mrtazz** [comment]
@atomicules are you also @atomicules on PyPi?

**Comment by mrtazz** [comment]
Just updated the password (re-added it in fact) so hopefully deploys should work now. Also gonna add you to PyPi as soon as you confirm the user name.

**Comment by atomicules** [comment]
Hi @mrtazz, yep I'm @atomicules on PyPi.

**Comment by mrtazz** [comment]
@atomicules alright, done! Added you as a maintainer.

**Comment by atomicules** [comment]
Thanks @mrtazz. 

Well, things are 90% working. Had to restart a build on Travis after 
it failed the first time but then it successfully deployed version 
0.3.1 to PyPi. Should have been version 0.3.7, but hey, can't have 
everything working 100% in one evening.

I think I need to tweak the `.travis.yml` further to prevent 
concurrent builds; I think the tagged build failed because the master 
one was running and that's why I had to restart the tagged one.

I'll leave that and figuring out deploying the correct version until 
tomorrow. And then I'll close this issue out.

**Comment by atomicules** [comment]
Too tired: I'd forgotten to update version number in `__init__.py`. 
That explains the deployment version number discrepancy.

**Comment by atomicules** [comment]
Closing this out now. Version is updated on PyPi and finally Travis deployment seems to be working :smile:

**Comment by markbao** [comment]
Thank you!
